name: Initialize Database

on:
  workflow_dispatch:
  
permissions:
  contents: read
  id-token: write

jobs:
  init_db:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: chetan8982/banking-2tier

          ref: main
          
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::865147227423:role/github-action
          aws-region: us-east-1

      - name: Upload file on s3
        run: |
          aws s3 mb s3://865147227423-devops-scripts --region us-east-1 2>/dev/null ||true
          aws s3 cp init.sql s3://865147227423-devops-scripts/init.sql
          aws s3 cp init.py s3://865147227423-devops-scripts/init.py
          echo "File Uploaded to Bucket..✅"