name : Test Workflows

on:
  push:
    branches:
      -main

jobs:
  working-job:
    run-on: ubuntu-latest

    steps:
      - name: Echo Message
        run : echo "Github Action is working successfully👍"

 